### ISSUE TITLE
Radius missing from Types import

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [Caffe1neAdd1ct/yamlloader#3]
```
232:
    basePrice: 3000.0
    description:
        en: "Consists of two components: a shell of titanium and a core of tungsten
            atoms suspended in plasma state. Railguns launch the shell directly, while
            particle blasters pump the plasma into a cyclotron and process the plasma
            into a bolt that is then fired.\r\n\r\n40% increased optimal range.\r\n27%
            reduced capacitor need."
    graphicID: 1331
    groupID: 85
    iconID: 1331
    marketGroupID: 106
    mass: 0.1
    name:
        de: Tungsten Charge L
        en: Tungsten Charge L
        fr: Charge de tungstène L
        ja: タングステン弾L
        ru: Tungsten Charge L
        zh: 钨质轨道弹 L
    portionSize: 100
    published: true
    radius: 10.0
    volume: 0.025
```
